name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  BINARY_NAME: hacky

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: hacky-linux-x86_64

          - os: windows-latest
            artifact: hacky-windows-x86_64.exe

          - os: macos-latest
            artifact: hacky-macos-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - name: Package artifact
        shell: bash
        run: |
          mkdir dist

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp target/release/${BINARY_NAME}.exe dist/${{ matrix.artifact }}
          else
            cp target/release/${BINARY_NAME} dist/${{ matrix.artifact }}
          fi

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
